config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews do
      resources :endorsements
    end
  end

  root to: "restaurants#index"

end

app/models/as_user_association_extensions.rb
module AsUserAssociationExtensions
  def created_by?(user)
    self.user == user
  end

  def destroy_as_user(user)
    destroy if created_by?(user)
  end
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include AsUserAssociationExtensions

  has_many :reviews, -> { extending WithUserAssociationExtension }, dependent: :destroy
  belongs_to :user

  validates :name, length: {minimum: 3}, uniqueness: true
  validates_presence_of :user

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  include AsUserAssociationExtensions

  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements, dependent: :destroy

  # validates_uniqueness_of :user
  validates :user, uniqueness: { scope: :restaurant }
  validates :rating, inclusion: (1..5)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants, dependent: :destroy

  has_many :reviews, dependent: :destroy
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
    attributes[:user] ||= user
    create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    redirect_to restaurant_path(@restaurant)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant.created_by?(current_user)
      flash[:notice] = "Error! You can't edit this restaurant!"
      redirect_to restaurants_path
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.destroy_as_user(current_user)
      flash[:notice] = 'Restaurant deleted successfully'
    else
      flash[:notice] = "Error! You can't delete this restaurant!"
    end
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :enforce_single_review, only: [:create, :new]

  def new
    find_restaurant
    @review = Review.new
  end

  def create
    find_restaurant
    @review = @restaurant.reviews.build_with_user(review_params, current_user)
    redirect_to restaurant_path(@restaurant) if @review.save
  end

  def destroy
    find_restaurant
    @review = Review.find(params[:id])
    @review.destroy_as_user(current_user)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

  def enforce_single_review
    find_restaurant
    if @restaurant.reviews.find_by(user_id: current_user).present?
      redirect_to restaurants_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = 5 - rating
    '★' * rating.round + "☆" * remainder
  end

  def created_since(review)
    current_time = Time.now
    time_difference = ((current_time - review.created_at) / 3600).floor
    'Created ' + pluralize(time_difference, 'hour') + ' ago'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <head>
    <title>RailsPractice</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path(), method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<%= link_to 'Add a restaurant', new_restaurant_path %>
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
    <h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
    <% if restaurant.created_by?(current_user) %>
      <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
      <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
    <% end %>
  <% end %>
<% else %>
  No restaurants yet!
<% end %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
<section id="errors" >
  <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>
<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h1><%= @restaurant.description %></h1>
<% unless @restaurant.reviews.find_by(user_id: current_user).present? %>
  <%= link_to "Review #{@restaurant.name}", new_restaurant_review_path(@restaurant) %>
<% end %>

<% if @restaurant.reviews.any? %>
  <% @restaurant.reviews.each do |review| %>
    <h2><%= review.thoughts %></h2>
    <h5><%= created_since(review) %></h5>
    <p><%= pluralize review.endorsements.count, 'endorsement' %></p>
    <%= link_to "Endorse review", restaurant_review_endorsements_path(@restaurant, review), method: :post %>
    <% if review.user_id == current_user.id %>
      <%= link_to "Delete review", restaurant_review_path(@restaurant, review), method: :delete %>
    <% end %>
  <% end %>
<% else %>
  <p>No reviews.</p>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>